const allSubdirectories = [
        { name: "Cyberpunk 2077", thumbnail: "../Cyberpunk 2077/thumbnail.jpg", url: "https://onelinkgames.site/Cyberpunk 2077/", categories: ["Action" ,"Open World","Sci-Fi"] },
        { name: "Grand Theft Auto VI", thumbnail: "../Grand Theft Auto VI/thumbnail.jpg", url: "https://onelinkgames.site/Grand Theft Auto VI/", categories: ["Action","Open World"] },
        { name: "Control", thumbnail: "../Control/thumbnail.jpg", url: "https://onelinkgames.site/Control/", categories: ["Adventure","Action","Sci-Fi"] },
        { name: "Elden Ring", thumbnail: "../Elden Ring/thumbnail.jpg", url: "https://onelinkgames.site/Elden Ring/", categories: ["Adventure","Open World"] },
        { name: "Hogwarts Legacy", thumbnail: "../Hogwarts Legacy/thumbnail.jpg", url: "https://onelinkgames.site/Hogwarts Legacy/", categories: ["Action","Open World"] },
        { name: "Horizon Zero Dawn", thumbnail: "../Horizon Zero Dawn/thumbnail.jpg", url: "https://onelinkgames.site/Horizon Zero Dawn/", categories: ["Action","Adventure"]},
        { name: "Lords of the Fallen", thumbnail: "../Lords of the Fallen/thumbnail.jpg", url: "https://onelinkgames.site/Lords of the Fallen/", categories: ["Action","RPG"]},
        { name: "NARUTO X BORUTO Ultimate Ninja Storm", thumbnail: "../NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS/thumbnail.jpg", url: "https://onelinkgames.site/NARUTO X BORUTO Ultimate Ninja STORM CONNECTIONS/", specialClass: "special-directory", categories: ["Action","Fighting"] },
        { name: "Microsoft Flight Simulator", thumbnail: "../Microsoft Flight Simulator/thumbnail.jpg", url: "https://onelinkgames.site/Microsoft Flight Simulator/", specialClass: "special-directory", categories: ["Action","Fighting"] },
        { name: "Forza Horizon 5", thumbnail: "../Forza Horizon 5/thumbnail.jpg", url: "https://onelinkgames.site/Forza Horizon 5", categories: "Racing" },
        { name: "MARVEL SPIDER-MAN MILES MORALES", thumbnail: "../MARVEL SPIDER-MAN MILES MORALES/thumbnail.jpg", url: "https://onelinkgames.site/MARVEL SPIDER-MAN MILES MORALES/", categories: ["Action","Adventure"], specialClass: "special-directory" },
        { name: "Red Dead Redemption 2", thumbnail: "../Red Dead Redemption 2/thumbnail.jpg", url: "https://onelinkgames.site/Red Dead Redemption 2/", categories: ["Action","Adventure","Open World"] },
        { name: "Grand Theft Auto V", thumbnail: "../Grand Theft Auto V/thumbnail.jpg", url: "https://onelinkgames.site/Grand Theft Auto V/", categories: ["Action","Open World"] },
        { name: "Alan Wake 2", thumbnail: "../Alan Wake 2/thumbnail.jpg", url: "https://onelinkgames.site/Alan Wake 2", categories: ["Horror","Survival"]},
        { name: "Call of Duty Black Ops Cold War", thumbnail: "../Call of Duty Black Ops Cold War/thumbnail.jpg", url: "https://onelinkgames.site/Call of Duty Black Ops Cold War/", categories: ["Action","Shooting"], specialClass: "special-directory"},
        { name: "Vosphia", thumbnail: "../Vosphia/thumbnail.jpg", url: "https://onelinkgames.site/Vosphia", categories: ["Open World","Survival"] },
        { name: "Ghost of Tsushima", thumbnail: "../Ghost of Tsushima/thumbnail.jpg", url: "https://onelinkgames.site/Ghost of Tsushima/", categories: ["Action","Adventure","Open World"] },
        { name: "Battlefield 1", thumbnail: "../Battlefield 1/thumbnail.jpg", url: "https://onelinkgames.site/Battlefield 1", categories: "Shooting" },
        { name: "Sekiro Shadow Die Twice", thumbnail: "../Sekiro Shadow Die Twice/thumbnail.jpg", url: "https://onelinkgames.site/Sekiro Shadow Die Twice/", categories: ["Action","Adventure"] },
        { name: "Starfield", thumbnail: "../Starfield/thumbnail.jpg", url: "https://onelinkgames.site/Starfield", categories: ["Action","Sci-Fi","RPG"] },
        { name: "FlatOut 4 Total Insanity", thumbnail: "../FlatOut 4 Total Insanity/thumbnail.jpg", url: "https://onelinkgames.site/FlatOut 4 Total Insanity/", categories: "Racing" },
        { name: "Gears of War Ultimate Edition Deluxe", thumbnail: "../Gears of War Ultimate Edition Deluxe/thumbnail.jpg", url: "https://onelinkgames.site/Gears of War Ultimate Edition Deluxe/", categories: ["Action","Shooting"] },
        { name: "FIFA 18", thumbnail: "../FIFA 18/thumbnail.jpg", url: "https://onelinkgames.site/FIFA 18/", categories: "Sports" },
];

export { allSubdirectories };
